# Use an official Node.js runtime as a parent image
FROM node:18

# Set environment variables
ENV NODE_ENV=production

# Set the working directory
WORKDIR /ailens-fashion

# Install dependencies
COPY package.json package-lock.json /ailens-fashion/
RUN npm install

# Copy the project code into the container
COPY . /ailens-fashion

# Build the Next.js app
RUN npm run build

# Expose the port the app runs on
EXPOSE 3000

# Start the Next.js application
CMD ["npm", "start"]